import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import "./globals.css";

const mitr = Mitr({
  variable: "--font-mitr",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Keswarin ❤️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body
        className={`${mitr.variable} overflow-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
